### ISSUE TITLE
Neovim - can't get the more advanced features working

### ISSUE THREAD

**Issue by tomoakley** [CircleCI-Public/circleci-yaml-language-server#283]
Hi, l've been working on a [circleci plugin for neovim](https://github.com/tomoakley/circleci.nvim), inspired by your vscode plugin.
I've added support for the LSP, which attaches to the buffer and is able to do some syntax highlighting, go-to-definition and find references. But the more advanced features you list in the readme don't appear to work, or I'm not sure what I need to do to get them to work, such as:
- Contextual documentation and usage hints: I assumed I could do this with `lua vim.lsp.buf.hover()` but it just says "no information available" on anything (workflows, pipelines, orbs, etc).
- Syntax validation and usage warnings: when I change the name of a workflow in the 'jobs' section to a name that doesn't exist, I'd expect it to tell me in the diagnostics, but when I use the vim.Isp diagnostics function it just says "No diagnostics available"
- Auto complete: it doesn't seem to suggest the names of piplines, parameters etc to me

The syntax highlighting appears to work, although if I start typing a new line, before I've finished it will change all of the text across the buffer to white. When I make the line valid yaml (e.g add a ':'), the syntax highlighting will kick in again.
I'm assuming I've implemented it wrong - the implementation in my plugin is here
https://github.com/tomoakley/circleci.nvim/blob/main/lua/nvim-circleci/lsp.lua. 

Would be very appreciative if anyone who knows Neovim/Lua could tell me what I've done wrong (I'm a bit of a newbie to writing plugins for neovim and handrolling LSP etc)

**Comment by JulesFaucherre** [comment]
Hey @tomoakley

Thanks a lot for the contribution!! That's really appreciable! On your problem, a lot of the LS features won't work because the LS needs to be passed few other assets. It is not documented so we'll make sure to add the doc here. I'll try to answer your three points here.

 - Unfortunately for the hover it might be complicated to handle it in NVim. the hover is not handled in the LS but directly in the VSCode extension, mainly because it depends on a JS library. If you want to handle the hover, here is how we do it in the extension:
   - Download the [JSON schema for the CircleCI config.yml from the SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/circleciconfig.json).
   - Register a hover provider with the VSCode API [`registerHoverProvider`](https://code.visualstudio.com/api/references/vscode-api#languages.registerHoverProvider).
   - Use the [vscode-json-languageservice](https://github.com/microsoft/vscode-json-languageservice) to provide hover from the downloaded schema.
 - Syntax validation is most likely not working because the LS is not passed the right JSON validation schema [here](https://github.com/tomoakley/circleci.nvim/blob/main/lua/nvim-circleci/lsp.lua#L32). The schema that should be passed is actually the one available in the repo at `/schema.json`, it is an asset we provide to every release. FWIW the [Mason registry package](https://github.com/mason-org/mason-registry/blob/main/packages/circleci-yaml-language-server/package.yaml) seem to be already handling the schema.json so it is most likely next to LS binary 😃 .
 - I suspect the autocompletion does not work because of the issue just above. If that still doesn't work after that, please come back to me! BTW to have the LS features working for private resources like private orbs or contexts you can authenticate the user with the following custom LS command. Example TS code:
```typescript
// Set the user token
await lsClient.sendRequest(`workspace/executeCommand`, {
  command: "setToken",
  arguments: ["<user-token>"],
})
// <optional> Set the host URL to request for self-hosted users
await lsClient.sendRequest(`workspace/executeCommand`, {
  command: "setSelfHostedUrl",
  arguments: ["<self-hosted-url>"],
})
```


Again, thanks for the great work you're doing! If there is anything else I can do to help please tell me!

_Side note_: I'm also working on making an CCI NVim pipeline viewer on my free time, I wanted to go for the LS configuration so I can fully appreciate the work you put there 😄 !

**Comment by tomoakley** [comment]
> FYI @tomoakley , I just [referenced](https://scarfolk.blogspot.com/2020/03/social-distancing-laws-1970.html) your plugin in the README as one of the clients of the Language Server.

awesome thanks! Although I think you may have put the wrong link 😅 
<img width="882" alt="Screenshot 2024-04-02 at 15 43 21" src="https://github.com/CircleCI-Public/circleci-yaml-language-server/assets/782523/72176c10-5330-48a9-b98c-884e36be2ec5">

**Comment by JulesFaucherre** [comment]
Damn my bad 😅

**Comment by JulesFaucherre** [comment]
By the way I also added a page of doc to help other people that would want to implement other LS client. Don't hesitate to look at it [here](https://github.com/CircleCI-Public/circleci-yaml-language-server/blob/main/ADD_A_CLIENT.md) and if you have any thing you think would be worth mentioning in the page please tell !

**Comment by tomoakley** [comment]
> By the way I also added a page of doc to help other people that would want to implement other LS client. Don't hesitate to look at it [here](https://github.com/CircleCI-Public/circleci-yaml-language-server/blob/main/ADD_A_CLIENT.md) and if you have any thing you think would be worth mentioning in the page please tell !

will have a think, thanks. Just fyi, I managed to get contextual documentation working - had to implement `yaml-language-server` and set schemas to download the circle schema. https://github.com/tomoakley/circleci.nvim/pull/9  - was much easier than I thought!
